// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVyq9IwkONquOGw9gZbg_O9-5Ogli0vM0',
    appId: '1:52237207926:web:11729bdacd829063e1d257',
    messagingSenderId: '52237207926',
    projectId: 'samaritan-74d6d',
    authDomain: 'samaritan-74d6d.firebaseapp.com',
    storageBucket: 'samaritan-74d6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0SyXglTWpJxxSMYeFU7qyFLKgFe_wy68',
    appId: '1:52237207926:android:5a6a295d79a554a8e1d257',
    messagingSenderId: '52237207926',
    projectId: 'samaritan-74d6d',
    storageBucket: 'samaritan-74d6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjrXv1btWxIiMHs3UYS__nG0vwukjQge4',
    appId: '1:52237207926:ios:d6afd51dc886dc83e1d257',
    messagingSenderId: '52237207926',
    projectId: 'samaritan-74d6d',
    storageBucket: 'samaritan-74d6d.firebasestorage.app',
    iosBundleId: 'com.example.samaritan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjrXv1btWxIiMHs3UYS__nG0vwukjQge4',
    appId: '1:52237207926:ios:d6afd51dc886dc83e1d257',
    messagingSenderId: '52237207926',
    projectId: 'samaritan-74d6d',
    storageBucket: 'samaritan-74d6d.firebasestorage.app',
    iosBundleId: 'com.example.samaritan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVyq9IwkONquOGw9gZbg_O9-5Ogli0vM0',
    appId: '1:52237207926:web:ebac0f49065b95d7e1d257',
    messagingSenderId: '52237207926',
    projectId: 'samaritan-74d6d',
    authDomain: 'samaritan-74d6d.firebaseapp.com',
    storageBucket: 'samaritan-74d6d.firebasestorage.app',
  );
}
